name: format

on:
  # push:
  #   branches: [master]
  schedule:
    - cron: "0 17,23,3,5,8,12 * * *"

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dp
        run: |
          sudo apt-get install openssl -y

      - name: dec db
        run: |
          openssl enc -aes-256-cbc -pbkdf2 -d -in format.db -out format -pass pass:"${{ secrets.OPENSSL_KEY }}"

      - id: set_commit_message
        run: echo ::set-output name=COMMIT_MSG::$(date "+%Y-%m-%d %H:%M:%S")

      - name: do
        run: |
          rm -rf .git
          git clone -b ${{ secrets.TARGET_BRANCH }} --depth 1 "https://github.com/${{ secrets.YOUR_GIT_NAME }}/${{ secrets.TARGET_NAME }}" target >/dev/null 2>&1
          mv format target/
          cd target
          sudo chmod a+x format
          ./format
          rm format

      - name: sync to github
        run: |
          cd target
          git config user.name    "${{ secrets.YOUR_GIT_NAME }}"
          git config user.email   "${{ secrets.YOUR_GIT_EMAIL }}"
          git add .
          THIS_GIT_STATUS=$(git status)
          if [[ "$(echo ${THIS_GIT_STATUS} | grep -o "nothing to commit, working tree clean")" == "nothing to commit, working tree clean" ]]
          then
            exit 0
          fi
          git commit -m "${{ steps.set_commit_message.outputs.COMMIT_MSG }}" >/dev/null 2>&1
          git push --repo "https://${{ secrets.YOUR_GIT_NAME }}:${{ secrets.YOUR_GIT_PWD }}@github.com/${{ secrets.YOUR_GIT_NAME }}/${{ secrets.TARGET_NAME }}.git" >/dev/null 2>&1

      - name: sync to gitee
        run: |
          cd target
          rm -rf .git
          git init
          git remote add origin "https://gitee.com/${{ secrets.YOUR_GITEE_NAME }}/${{ secrets.TARGET_NAME }}.git"  >/dev/null 2>&1
          git config user.name    "${{ secrets.YOUR_GITEE_NAME }}"
          git config user.email   "${{ secrets.YOUR_GITEE_EMAIL }}"
          git add .
          git commit -m "${{ steps.set_commit_message.outputs.COMMIT_MSG }}" >/dev/null 2>&1
          git checkout -b feeds  >/dev/null 2>&1
          git branch -d master  >/dev/null 2>&1
          git push -f --repo "https://${{ secrets.YOUR_GITEE_NAME }}:${{ secrets.YOUR_GITEE_PWD }}@gitee.com/${{ secrets.YOUR_GITEE_NAME }}/${{ secrets.TARGET_NAME }}.git"  >/dev/null 2>&1
