name: format

on:
  push:
    branches: [master]
  # schedule:
  #   - cron: "0 17,23,3,5,8,12,15 * * *"

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install dp
        run: |
          sudo apt-get install openssl -y

      - name: dec db
        run: |
          openssl enc -aes-256-cbc -pbkdf2 -d -in format.db -out format -pass pass:"${{ secrets.OPENSSL_KEY }}"

      - id: set_commit_message
        run: echo ::set-output name=COMMIT_MSG::$(date "+%Y-%m-%d %H:%M:%S")

      - name: do
        run: |
          rm -rf .git
          git clone -b ${{ secrets.TARGET_BRANCH }} --depth 1 "https://github.com/${{ secrets.YOUR_GIT_NAME }}/${{ secrets.TARGET_NAME }}" target >/dev/null 2>&1
          git clone -b pages --depth 1 "https://github.com/${{ secrets.YOUR_GIT_NAME }}/${{ secrets.TARGET_NAME }}" target2 >/dev/null 2>&1
          mv format target/
          cd target
          sudo chmod a+x format
          ./format
          rm format

      - name: sync to github
        id: sync_to_github
        run: |
          cd target
          git config user.name    "${{ secrets.YOUR_GIT_NAME }}"
          git config user.email   "${{ secrets.YOUR_GIT_EMAIL }}"
          # git add .
          # THIS_GIT_STATUS=$(git status)
          # if [[ "$(echo ${THIS_GIT_STATUS} | grep -o "nothing to commit, working tree clean")" == "nothing to commit, working tree clean" ]]
          # then
          #   exit 0
          # fi
          # git commit -m "${{ steps.set_commit_message.outputs.COMMIT_MSG }}" >/dev/null 2>&1
          # git push --repo "https://${{ secrets.YOUR_GIT_NAME }}:${{ secrets.YOUR_GIT_PWD }}@github.com/${{ secrets.YOUR_GIT_NAME }}/${{ secrets.TARGET_NAME }}.git" >/dev/null 2>&1
          git rev-parse --short HEAD >../VERSION

      - name: sync to github 2
        run: |
          cd target2
          git config user.name    "${{ secrets.YOUR_GIT_NAME }}"
          git config user.email   "${{ secrets.YOUR_GIT_EMAIL }}"
          mv ../VERSION ./VERSION
          git add VERSION
          git commit -m "${{ steps.set_commit_message.outputs.COMMIT_MSG }}" >/dev/null 2>&1
          git push --repo "https://${{ secrets.YOUR_GIT_NAME }}:${{ secrets.YOUR_GIT_PWD }}@github.com/${{ secrets.YOUR_GIT_NAME }}/${{ secrets.TARGET_NAME }}.git" >/dev/null 2>&1

      - name: sync to gitee
        run: |
          cd target
          rm -rf .git
          git init
          git remote add origin "https://gitee.com/${{ secrets.YOUR_GITEE_NAME }}/${{ secrets.TARGET_NAME }}.git"  >/dev/null 2>&1
          git config user.name    "${{ secrets.YOUR_GITEE_NAME }}"
          git config user.email   "${{ secrets.YOUR_GITEE_EMAIL }}"
          git add .
          git commit -m "${{ steps.set_commit_message.outputs.COMMIT_MSG }}" >/dev/null 2>&1
          git checkout -b feeds  >/dev/null 2>&1
          git branch -d master  >/dev/null 2>&1
          git push -f --repo "https://${{ secrets.YOUR_GITEE_NAME }}:${{ secrets.YOUR_GITEE_PWD }}@gitee.com/${{ secrets.YOUR_GITEE_NAME }}/${{ secrets.TARGET_NAME }}.git"  >/dev/null 2>&1

      - name: sync to gitee 2
        run: |
          cd target2
          rm -rf .git
          git init
          git remote add origin "https://gitee.com/${{ secrets.YOUR_GITEE_NAME }}/${{ secrets.TARGET_NAME }}.git"  >/dev/null 2>&1
          git config user.name    "${{ secrets.YOUR_GITEE_NAME }}"
          git config user.email   "${{ secrets.YOUR_GITEE_EMAIL }}"
          git add .
          git commit -m "${{ steps.set_commit_message.outputs.COMMIT_MSG }}" >/dev/null 2>&1
          git checkout -b pages  >/dev/null 2>&1
          git branch -d master  >/dev/null 2>&1
          git push -f --repo "https://${{ secrets.YOUR_GITEE_NAME }}:${{ secrets.YOUR_GITEE_PWD }}@gitee.com/${{ secrets.YOUR_GITEE_NAME }}/${{ secrets.TARGET_NAME }}.git"  >/dev/null 2>&1

      - name: refresh
        run: |
          sleep 5
          echo "requesting gitee access token"
          SECRETS_GITEE_ACCESS_TOKEN=$(curl --silent -X POST --data-urlencode "grant_type=password" --data-urlencode "username=${{ secrets.YOUR_GITEE_NAME }}" --data-urlencode "password=${{ secrets.YOUR_GITEE_PWD }}" --data-urlencode "client_id=${{ secrets.YOUR_GITEE_CLIENT_ID }}" --data-urlencode "client_secret=${{ secrets.YOUR_GITEE_CLIENT_SECRET }}" --data-urlencode "scope=projects" "${{ secrets.PROXY_URL }}https://gitee.com/oauth/token" |  grep -oP '(?<="access_token":")[\da-f]+(?=")')
          if [ "${SECRETS_GITEE_ACCESS_TOKEN}" = "" ]; then
              echo "request gitee access token failed"

              exit 1
          fi


          echo "rebuilding gitee pages"
          rebuild_result=$(curl --silent -X POST --header 'Content-Type: application/json;charset=UTF-8' "${{ secrets.PROXY_URL }}https://gitee.com/api/v5/repos/${{ secrets.YOUR_GITEE_NAME }}/${{ secrets.TARGET_NAME }}/pages/builds" -d "{\"access_token\":\"${SECRETS_GITEE_ACCESS_TOKEN}\"}")
          if [ "$(echo "${rebuild_result}"  | grep -oP "(?<=\")queued(?=\")")" != "queued" ]; then
              echo "rebuild gitee pages failed: ${rebuild_result}"

              exit 1         
          fi
